####################### SCHEDULE ##################################
schedules:
  - cron: "0 19 * * *"
    displayName: Nightly build
    branches:
      include:
        - main
    always: true
    batch: true

####################### TRIGGER ##################################
trigger:
    - main

####################### PIPELINE NAME ##################################
name: $(ReleaseVersion).$(date:yyyy).$(date:MMdd)$(rev:.r)

####################### VARIABLES ##################################
variables:
  - group: ePortfolio
  - name: solution
    value: '**/Portfolio.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: BuildVersion
    value: '$(Build.BuildNumber)'

####################### AGENT POOL ##################################
pool: default

####################### RESOURCES ##################################
# resources:
#   repositories:
#     - repository: MCLifeLeader
#       type: github
#       name: ePortfolio
#       endpoint: ePortfolio

####################### STAGES ##################################

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    MSBuildArgs: '/p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:PackageLocation="$(build.artifactStagingDirectory)" /p:Version=$(BuildVersion) /p:EnvironmentName=Production /p:BuildingInsideVisualStudio=false'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Artifacts to Staging Directory'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'