####################### SCHEDULE ##################################
schedules:
  - cron: "0 19 * * *"
    displayName: Nightly build
    branches:
      include:
        - main
    always: true
    batch: true

####################### TRIGGER ##################################
trigger:
    - main

####################### PIPELINE NAME ##################################
name: $(ReleaseVersion).$(date:yyyy).$(date:MMdd)$(rev:.r)

####################### VARIABLES ##################################
variables:
  - group: ePortfolio
  - name: solution
    value: '**/Portfolio.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: BuildVersion
    value: '$(Build.BuildNumber)'

####################### AGENT POOL ##################################
pool: default

####################### RESOURCES ##################################
# resources:
#   repositories:
#     - repository: MCLifeLeader
#       type: github
#       name: ePortfolio
#       endpoint: ePortfolio

####################### STAGES ##################################

steps:

# Build the solution
- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) /p:Version=$(BuildVersion) /p:EnvironmentName=Production'

# Publish the project to the artifact staging directory
- task: DotNetCoreCLI@2
  displayName: 'Publish Project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:Version=$(BuildVersion) /p:EnvironmentName=Production'
    zipAfterPublish: false

# Publish the build artifacts to Azure DevOps artifact store
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'